# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2f67173d727d94c8443f2abe44b001f4ff1c598bcdd2c370adea863b2a0c4166f09679011b7bc8bceaf2cd1dfbfac30676850e25577ca5efea4e3bf084c474f

test:
  secret_key_base: 62712769d99e42c0ef1f8511f93b2b47522edfb7bef25d39a0ed3406052cae9cd550ff283b4fe1dc43edaca5c9295d656e4f9a9e2e6818e1551dbb5174139ab1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
